name: Build Android

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew assembleRelease
